<?php include '../include/functions.php';
header('content-type: application/json'); ?>
[
    {
        "id": "node1",
        "title": "Ban chung cu Vinhomes Nguyen Trai",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h1.jpg",
        "latitude": 21.12,
        "longitude": 106.21,
        "price": 12000,
        "area": 100.0,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Trai",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Dong",
        "sophongngu": 2,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hung",
        "diachi": "Ha Noi",
        "dienthoai": "09121231",
        "didong": "102313",
        "email": "haquochung@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user1",
        "type": "typereal1",
        "duanid": "duan1",
        "modid": "mod1"
    },
    {
        "id": "node2",
        "title": "chung cu Vinhomes Nguyen Chi Thanh",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h2.jpg",
        "latitude": 21.02,
        "longitude": 105.8,
        "price": 12000,
        "area": 90.0,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Dong",
        "sophongngu": 2,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal2",
        "duanid": "duan2",
        "modid": "mod1"
    },
    {
        "id": "node3",
        "title": "chung cu Vinhomes Nguyen Chi Thanh 2",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h3.jpg",
        "latitude": 21.08,
        "longitude": 106.01,
        "price": 12000,
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal7",
        "duanid": "duan1",
        "modid": "mod1"
    },
    {
        "id": "node4",
        "title": "chung cu Vinhomes Nguyen Chi Thanh 2",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h4.jpg",
        "latitude": 21.09,
        "longitude": 106.01,
        "price": 12000,
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal7",
        "duanid": "duan1",
        "modid": "mod1"
    },
    {
        "id": "node5",
        "title": "chung cu Vinhomes Nguyen Chi Thanh 2",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h5.jpg",
        "latitude": 21.07,
        "longitude": 106.01,
        "price": 12000,
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal7",
        "duanid": "duan1",
        "modid": "mod1"
    }
]
