<?php include '../include/functions.php';
header('content-type: application/json'); ?>
[
    {
        "id": "node1",
        "title": "Ban chung cu Vinhomes Nguyen Trai",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h1.jpg",
        "latitude": 21.031885,
        "longitude": 105.813755,
        "price": "1 tỷ",
        "area": 100.0,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Trai",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "address": "15 Nguyen Trai, Thanh Xuan, Ha Noi",
        "huong": "Dong",
        "sophongngu": 2,
        "details": "<p>Founded in 1824, the Porcelain Factory of Vista Alegre was the first industrial unit dedicated to porcelain production in Portugal. For the foundation and success of this risky industrial development was crucial the spirit of persistence of its founder, José Ferreira Pinto Basto. Leading figure in Portuguese society of the nineteenth century farm owner, daring dealer, wisely incorporated the liberal ideas of the century, having become \"the first example of free enterprise\" in Portugal.</p><p class='bold'>Contacts</p><p>VISTA ALEGRE ATLANTIS, SA<br>3830-292 Ílhavo - Portugal<br><br>Phone. +351 234 320 600<br>e-mail: geral@vaa.pt<br>www: www.myvistaalegre.com</p>",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hung",
        "diachi": "Ha Noi",
        "dienthoai": "09121231",
        "didong": "102313",
        "email": "haquochung@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user1",
        "type": "typereal1",
        "duanid": "duan1",
        "type_action": "1",
        "modid": "mod1"
    },
    {
        "id": "node2",
        "title": "chung cu Vinhomes Nguyen Chi Thanh",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h2.jpg",
        "latitude": 21.027666,
        "longitude": 105.824105,
        "price": "500 triệu",
        "area": 90.0,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "address": "15 Nguyen Trai, Thanh Xuan, Ha Noi",
        "huong": "Dong",
        "sophongngu": 2,
        "details": "<p>Founded in 1824, the Porcelain Factory of Vista Alegre was the first industrial unit dedicated to porcelain production in Portugal. For the foundation and success of this risky industrial development was crucial the spirit of persistence of its founder, José Ferreira Pinto Basto. Leading figure in Portuguese society of the nineteenth century farm owner, daring dealer, wisely incorporated the liberal ideas of the century, having become \"the first example of free enterprise\" in Portugal.</p><p class='bold'>Contacts</p><p>VISTA ALEGRE ATLANTIS, SA<br>3830-292 Ílhavo - Portugal<br><br>Phone. +351 234 320 600<br>e-mail: geral@vaa.pt<br>www: www.myvistaalegre.com</p>",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal2",
        "duanid": "duan2",
        "type_action": "2",
        "modid": "mod1"
    },
    {
        "id": "node3",
        "title": "chung cu Vinhomes Nguyen Chi Thanh 3",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h3.jpg",
        "latitude": 21.020827,
        "longitude": 105.791488,
        "price": "800 triệu",
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "address": "15 Nguyen Trai, Thanh Xuan, Ha Noi",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "<p>Founded in 1824, the Porcelain Factory of Vista Alegre was the first industrial unit dedicated to porcelain production in Portugal. For the foundation and success of this risky industrial development was crucial the spirit of persistence of its founder, José Ferreira Pinto Basto. Leading figure in Portuguese society of the nineteenth century farm owner, daring dealer, wisely incorporated the liberal ideas of the century, having become \"the first example of free enterprise\" in Portugal.</p><p class='bold'>Contacts</p><p>VISTA ALEGRE ATLANTIS, SA<br>3830-292 Ílhavo - Portugal<br><br>Phone. +351 234 320 600<br>e-mail: geral@vaa.pt<br>www: www.myvistaalegre.com</p>",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal3",
        "duanid": "duan1",
        "type_action": "1",
        "modid": "mod1"
    },
    {
        "id": "node4",
        "title": "chung cu Vinhomes Nguyen Chi Thanh 4",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h4.jpg",
        "latitude": 21.046274,
        "longitude": 105.844371,
        "price": "12.5 tỷ",
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "address": "15 Nguyen Trai, Thanh Xuan, Ha Noi",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal4",
        "duanid": "villa",
        "type_action": "1",
        "modid": "mod1"
    },
    {
        "id": "node5",
        "title": "chung cu Vinhomes Nguyen Chi Thanh 5",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h5.jpg",
        "latitude": 21.0227,
        "longitude": 105.844351,
        "price": "1 tỷ",
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "address": "15 Nguyen Trai, Thanh Xuan, Ha Noi",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "<p>Founded in 1824, the Porcelain Factory of Vista Alegre was the first industrial unit dedicated to porcelain production in Portugal. For the foundation and success of this risky industrial development was crucial the spirit of persistence of its founder, José Ferreira Pinto Basto. Leading figure in Portuguese society of the nineteenth century farm owner, daring dealer, wisely incorporated the liberal ideas of the century, having become \"the first example of free enterprise\" in Portugal.</p><p class='bold'>Contacts</p><p>VISTA ALEGRE ATLANTIS, SA<br>3830-292 Ílhavo - Portugal<br><br>Phone. +351 234 320 600<br>e-mail: geral@vaa.pt<br>www: www.myvistaalegre.com</p>",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal5",
        "duanid": "duan1",
        "type_action": "2",
        "modid": "mod1"
    },
    {
        "id": "node6",
        "title": "chung cu Vinhomes Nguyen Chi Thanh 6",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h6.jpg",
        "latitude": 21.0237,
        "longitude": 105.814351,
        "price": "2.05 tỷ",
        "area": 180.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "address": "15 Nguyen Trai, Thanh Xuan, Ha Noi",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "<p>Founded in 1824, the Porcelain Factory of Vista Alegre was the first industrial unit dedicated to porcelain production in Portugal. For the foundation and success of this risky industrial development was crucial the spirit of persistence of its founder, José Ferreira Pinto Basto. Leading figure in Portuguese society of the nineteenth century farm owner, daring dealer, wisely incorporated the liberal ideas of the century, having become \"the first example of free enterprise\" in Portugal.</p><p class='bold'>Contacts</p><p>VISTA ALEGRE ATLANTIS, SA<br>3830-292 Ílhavo - Portugal<br><br>Phone. +351 234 320 600<br>e-mail: geral@vaa.pt<br>www: www.myvistaalegre.com</p>",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal6",
        "duanid": "duan1",
        "type_action": "2",
        "modid": "mod1"
    },
    {
        "id": "node7",
        "title": "chung cu Vinhomes Nguyen Chi Thanh 7",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h7.jpg",
        "latitude": 21.02437,
        "longitude": 105.864151,
        "price": "800 triệu",
        "area": 60.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "address": "15 Nguyen Trai, Thanh Xuan, Ha Noi",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "<p>Founded in 1824, the Porcelain Factory of Vista Alegre was the first industrial unit dedicated to porcelain production in Portugal. For the foundation and success of this risky industrial development was crucial the spirit of persistence of its founder, José Ferreira Pinto Basto. Leading figure in Portuguese society of the nineteenth century farm owner, daring dealer, wisely incorporated the liberal ideas of the century, having become \"the first example of free enterprise\" in Portugal.</p><p class='bold'>Contacts</p><p>VISTA ALEGRE ATLANTIS, SA<br>3830-292 Ílhavo - Portugal<br><br>Phone. +351 234 320 600<br>e-mail: geral@vaa.pt<br>www: www.myvistaalegre.com</p>",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal7",
        "duanid": "duan1",
        "type_action": "2",
        "modid": "mod1"
    },
    {
        "id": "node8",
        "title": "chung cu Vinhomes Nguyen Chi Thanh 8",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h8.jpg",
        "latitude": 21.02973,
        "longitude": 105.874751,
        "price": "8 tỷ",
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "address": "8 Bong bong, Thanh Xuan, Ha Noi",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "<p>Founded in 1824, the Porcelain Factory of Vista Alegre was the first industrial unit dedicated to porcelain production in Portugal. For the foundation and success of this risky industrial development was crucial the spirit of persistence of its founder, José Ferreira Pinto Basto. Leading figure in Portuguese society of the nineteenth century farm owner, daring dealer, wisely incorporated the liberal ideas of the century, having become \"the first example of free enterprise\" in Portugal.</p><p class='bold'>Contacts</p><p>VISTA ALEGRE ATLANTIS, SA<br>3830-292 Ílhavo - Portugal<br><br>Phone. +351 234 320 600<br>e-mail: geral@vaa.pt<br>www: www.myvistaalegre.com</p>",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal8",
        "duanid": "duan1",
        "type_action": "2",
        "modid": "mod1"
    },
    {
        "id": "node9",
        "title": "chung cu Vinhomes 9",
        "avatar": "<?php echo MAIN_URL ?>/data/images/h9.jpg",
        "latitude": 21.02973,
        "longitude": 105.874751,
        "price": "9 tỷ",
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "address": "9 Hai Ba Trung, Thanh Xuan, Ha Noi",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "<p>Founded in 1824, the Porcelain Factory of Vista Alegre was the first industrial unit dedicated to porcelain production in Portugal. For the foundation and success of this risky industrial development was crucial the spirit of persistence of its founder, José Ferreira Pinto Basto. Leading figure in Portuguese society of the nineteenth century farm owner, daring dealer, wisely incorporated the liberal ideas of the century, having become \"the first example of free enterprise\" in Portugal.</p><p class='bold'>Contacts</p><p>VISTA ALEGRE ATLANTIS, SA<br>3830-292 Ílhavo - Portugal<br><br>Phone. +351 234 320 600<br>e-mail: geral@vaa.pt<br>www: www.myvistaalegre.com</p>",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typenode": true,
        "userid": "user2",
        "type": "typereal8",
        "duanid": "duan1",
        "type_action": "2",
        "modid": "mod1"
    }
]
